# Importando um Dataset

| | |
|---|---|
| **Autor** | Cristian Matias de Souza — Analista de Dados (N3) |
| **Criado em** | 12/09/2026 20:18 |
| **Versão** | 2.0 (convertido para notebook em 11/10/2026) |
| **Dependências** | Python 3.14, pandas |

**Objetivo:** importar `Dataset/GazPrice.csv` (preços de combustíveis da ANP por semana, região, estado e produto) e fazer a primeira inspeção: tipo do objeto, dimensões (`shape`), estrutura (`info`) e amostra (`head`).

## 1. Importações

In [10]:
from pathlib import Path
import pandas as pd

## 2. Opções de exibição

Mostramos **todas as colunas** (são 20), mas **não** liberamos todas as linhas:
esta base tem mais de 100 mil registros e exibi-los de uma vez travaria o notebook.
Para olhar os dados usamos `head()`, que mostra só o começo.

In [11]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 3. Caminho do arquivo e colunas de data

O notebook roda a partir da **própria pasta** (`notebooks/`), que é o padrão do Antigravity,
do VS Code e do JupyterLab. Por isso usamos `..` para subir um nível até a raiz do projeto
e chegar na pasta `Dataset`.

As colunas de data são informadas em `parse_dates` para já entrarem como
`datetime` (data de verdade), e não como texto.

In [12]:
ARQUIVO = Path("../Dataset/GazPrice.csv")
COLUNAS_DATA = ["DATA INICIAL", "DATA FINAL"]

## 4. Carregando o dataset

`sep=","` e `encoding="utf-8"` já são o padrão do `read_csv`, então não precisam ser passados.
Se o arquivo não existir, o próprio pandas avisa com um `FileNotFoundError`.

In [13]:
df_gaz = pd.read_csv(ARQUIVO, parse_dates=COLUNAS_DATA)
print(f"Arquivo: {ARQUIVO.name} ({ARQUIVO.stat().st_size:,} bytes)")

Arquivo: GazPrice.csv (14,040,204 bytes)

## 5. Tipo do objeto

Confirma que o resultado da leitura é um `pandas.DataFrame`.

In [14]:
type(df_gaz)

pandas.DataFrame

## 6. Dimensões com `shape`

`shape` é um **atributo** (sem parênteses) e devolve uma tupla `(linhas, colunas)`.

In [15]:
linhas, colunas = df_gaz.shape
print(f"Shape: {df_gaz.shape}")
print(
    f"O DataFrame possui {linhas} linhas/observações/registros "
    f"e {colunas} colunas/atributos/variáveis."
)

Shape: (103392, 20)
O DataFrame possui 103392 linhas/observações/registros e 20 colunas/atributos/variáveis.

## 7. Estrutura com `info()`

`info()` é um **método** (com parênteses): mostra o tipo de cada coluna,
quantos valores não nulos existem e quanta memória o DataFrame ocupa.
Repare que as colunas de data aparecem como `datetime64`.

In [16]:
df_gaz.info()

<class 'pandas.DataFrame'>
RangeIndex: 103392 entries, 0 to 103391
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   103392 non-null  datetime64[us]
 1   DATA FINAL                     103392 non-null  datetime64[us]
 2   REGIÃO                         103392 non-null  str
 3   ESTADO                         103392 non-null  str
 4   PRODUTO                        103392 non-null  str
 5   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 6   UNIDADE DE MEDIDA              103392 non-null  str
 7   PREÇO MÉDIO REVENDA            103392 non-null  float64
 8   DESVIO PADRÃO REVENDA          103392 non-null  float64
 9   PREÇO MÍNIMO REVENDA           103392 non-null  float64
 10  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 11  MARGEM MÉDIA REVENDA           103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 18  MÊS                            103392 non-null  int64
 19  ANO                            103392 non-null  int64
dtypes: datetime64[us](2), float64(11), int64(3), str(4)
memory usage: 15.8 MB

## 8. Amostra com `head()`

`head(n)` retorna apenas as `n` primeiras linhas (o padrão é 5).

In [17]:
df_gaz.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

## 9. Atribuindo Valores

Atribuindo valores em alterações de conteudos

In [18]:
df_gaz.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

### Atribuindo Constantes

In [19]:
produto_view = df_gaz['PRODUTO']                                    # No pandas 3 (Copy-on-Write), funciona como uma cópia independente.
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
103387                 GNV
103388                 GNV
103389                 GNV
103390                 GNV
103391                 GNV
Name: PRODUTO, Length: 103392, dtype: str

In [20]:
produto_copy_bkp = df_gaz['PRODUTO'].copy()                        # Cópia explícita: no pandas 3 dá o mesmo resultado da célula acima.
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
103387                 GNV
103388                 GNV
103389                 GNV
103390                 GNV
103391                 GNV
Name: PRODUTO, Length: 103392, dtype: str

In [27]:
df_gaz['PRODUTO'] = 'Combustivel'                                   # Substitui o dado para "combustivel"
df_gaz.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Combustivel,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Combustivel,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Combustivel,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Combustivel,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Combustivel,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [22]:
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
103387                 GNV
103388                 GNV
103389                 GNV
103390                 GNV
103391                 GNV
Name: PRODUTO, Length: 103392, dtype: str

In [23]:
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
103387                 GNV
103388                 GNV
103389                 GNV
103390                 GNV
103391                 GNV
Name: PRODUTO, Length: 103392, dtype: str

### Por que `produto_view` não mudou? (Copy-on-Write)

Repare que, mesmo depois de `df_gaz['PRODUTO'] = 'Combustivel'`, **as duas variáveis
continuaram com `ETANOL HIDRATADO`**.

Isso acontece por causa do **Copy-on-Write** ("copia ao escrever"), que é o padrão desde o **pandas 3.0**:

- Selecionar uma coluna (`df_gaz['PRODUTO']`) **funciona como uma cópia**. Por baixo dos panos,
  o pandas só copia os dados de verdade no momento em que alguém tenta alterar, o que economiza memória.
- Por isso, **alterar o DataFrame nunca muda uma variável separada antes**, e alterar a variável
  nunca muda o DataFrame.
- Para **separar** uma coluna, o `.copy()` deixou de ser necessário. Ele continua útil para deixar
  a intenção clara no código ou se você usar uma versão antiga do pandas (antes da 3.0), em que
  `produto_view` podia, sim, ser afetada.

> Regra prática no pandas 3: para mudar o DataFrame, altere **o próprio DataFrame**
> (`df_gaz['PRODUTO'] = ...` ou `df_gaz.loc[linha, 'PRODUTO'] = ...`), e não uma variável que veio dele.